<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DTOs\Request\**" />
    <Compile Remove="DTOs\Response\**" />
    <EmbeddedResource Remove="DTOs\Request\**" />
    <EmbeddedResource Remove="DTOs\Response\**" />
    <None Remove="DTOs\Request\**" />
    <None Remove="DTOs\Response\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Extensions\" />
    <Folder Include="Mappers\" />
    <Folder Include="Services\" />
    <Folder Include="Validators\Configuration\" />
    <Folder Include="Validators\Controllers\" />
    <Folder Include="Validators\Filters\" />
    <Folder Include="Validators\Middleware\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shuryan.Core\Shuryan.Core.csproj" />
  </ItemGroup>

</Project>
